require "uws"
require "time"
require "json"

# #Graceful Shutdown on SIGINT
$app = nil
Signal.trap("INT") { 
    $app.close()
  exit
}


main_thread = Thread.new {
    #if you dont want SSL just use $app = UWS::App.new()
    $app = UWS::SSLApp.new({
      key_file_name: "./misc/key.pem", #generated by ./test.sh
      cert_file_name: "./misc/cert.pem", #generated by ./test.sh
      passphrase: "1234"
    })
    
    $app.get("/", lambda {|response, request| response.end("Hello, World!")})
    .listen(8082, lambda {|config| puts "Listening on port #{config.port}" })
    .run()
}

main_thread.join
